export const RUN_BUILD_PENDING = 'RUN_BUILD_PENDING';
export const RUN_BUILD_SUCCESS = 'RUN_BUILD_SUCCESS';
export const RUN_BUILD_FAIL = 'RUN_BUILD_FAIL';

export const FETCH_BUILDS_PENDING = 'FETCH_BUILDS_PENDING';
export const FETCH_BUILDS_SUCCESS = 'FETCH_BUILDS_SUCCESS';
export const FETCH_BUILDS_FAIL = 'FETCH_BUILDS_FAIL';
